# Generated by Django 4.1.7 on 2023-03-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='truckmodel',
            fields=[
                ('truck_id', models.TextField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, default=None, null=True)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=9, null=True)),
            ],
            options={
                'db_table': 'trucks_details',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='sku_model',
            fields=[
                ('sku', models.TextField(primary_key=True, serialize=False)),
                ('quantity', models.SmallIntegerField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='app.truckmodel')),
            ],
            options={
                'db_table': 'sku_details',
            },
        ),
    ]
