# Generated by Django 4.1.7 on 2023-03-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_phone_number_phoneotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
